PROJECTNAME=TCScript
INNOSETUP="C:\Program Files (x86)\Inno Setup 5\Compil32.exe"

release: buildsetup source

source:
	hg archive -t zip $(PROJECTNAME)-src.zip

buildsetup: setup\$(PROJECTNAME).iss
	$(INNOSETUP) /cc setup\$(PROJECTNAME).iss
