#!/bin/sh
### BEGIN INIT INFO
# Provides:          tcscript 
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Automated TrueCrypt mounting and dismounting shell script.
### END INIT INFO

## Define LSB log_* functions.
## Note: Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

## Include user configuration
. /etc/tcscript.conf

case "${1}" in

    start)
        sudo -u "${USERNAME}" /usr/bin/tcscript --mount
        exit "${?}"
    ;;
    
    stop)
        sudo -u "${USERNAME}" /usr/bin/tcscript --dismount
        exit "${?}"
    ;;

    restart|force-reload)
        ${0} stop && sleep 2 && ${0} start
    ;;

    status)
        if ( mount -l | grep "${MOUNTPATH}" > /dev/null ); then
            log_success_msg "TCScript has mounted \"${MOUNTPATH}\""
            exit 0
        else
            log_failure_msg "TCScript has not mounted \"${MOUNTPATH}\""
            exit 1
        fi
    ;;
    
    *)
        echo "Usage: ${0} { start | stop | restart | force-reload | status }"
        exit 0
    ;;
    
esac
