#!/bin/sh
### BEGIN INIT INFO
# Provides:          tcscript 
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Automated TrueCrypt mounting and dismounting shell script.
### END INIT INFO

## Include user configuration
. /etc/tcscript/tcscript.conf

case "${1}" in

    start)
        sudo -u "${USERNAME}" sh /usr/bin/tcscript --mount
        exit "${?}"
    ;;
    
    stop)
        sudo -u "${USERNAME}" sh /usr/bin/tcscript --dismount
        exit "${?}"
    ;;

    *)
        echo "Usage: ${0} { start | stop }"
        exit 0
    ;;
    
esac
