.TH tcscript 1 "July 2014" "" "TrueCrypt script"

.SH NAME
\fBtcscript\fP - TrueCrypt mounting and dismounting script

.SH SYNOPSIS
.nf
.fam C
\fBtcscript\fP [Action] [Options]
Action: [\fB--mount\fP | \fB--dismount\fP | \fB--auto\fP | \fB--version\fP | \fB--help\fP]
Options: [\fB--debug\fP | \fB--silent\fP | \fB--interactive\fP]
.fam T
.fi

.SH DESCRIPTION
\fBtcscript\fP simplifies the mounting and dismounting routine of a TrueCrypt volume. TrueCrypt is needed anyway! It is recommend that a keyfile is used for the decryption of the volume. Then this keyfile can be on a external SD card (token). The script can be used to mount a TrueCrypt volume while booting. The volume only gets mounted if the token is plugged in. On shutdown the volume gets automatically dismounted.

.TP
To enable this automatically mount/dismount:
~# update-rc.d tcscript defaults

.TP
To disable it:
~# update-rc.d tcscript remove
.PP

\fBtcscript\fP can use Zenity to display GTK+ messages by using the --interactive option. To configure \fBtcscript\fP the /etc/tcscript.conf has to be edited.

.SH ACTION

.TP
\fB--mount\fR, \fB-m\fR
Mounts a decrypted TrueCrypt volume.

.TP
\fB--dismount\fR, \fB-d\fR
Dismounts a TrueCrypt volume.

.TP 
\fB--auto\fR, \fB-a\fR
Either mounts a TrueCrypt volume if it is dismounted or dismounts a TrueCrypt volume if it is mounted.

.TP
\fB--version\fR, \fB-v\fR
Prints version and exits.

.TP
\fB--help\fR
Shows summary of options.
.PP

.SH OPTIONS

.TP
\fB--silent\fR
Suppress errors if keyfile or token device was not found.

.TP
\fB--interactive\fR
Uses Zenity to show GTK+ messages instead of console output.

.TP
\fB--debug\fR
Prints debug messages. NOTE: If set, other options will be ignored!
.PP

.SH FILES
/etc/tcscript.conf

.SH AUTHORS
Philipp Meisberger <team@pm-codeworks.de> 

Please send bug reports to this mail address. Visit http://www.pm-codeworks.de for more interesting projects.
