#!/bin/sh

DIRECTORY=tcscript

if ( ! test -d "$DIRECTORY" ); then
  echo "The directory does not exists!"
  exit 1
fi

cp -R "$DIRECTORY" "${DIRECTORY}_temp/"
dpkg --build "${DIRECTORY}_temp/" "${DIRECTORY}.deb"
chown 1000:1000 "${DIRECTORY}.deb"

rm -R "${DIRECTORY}_temp/"
